version: '2'
services:
  nginx:
    image: nginx:1.15-alpine
    volumes:
      - ./../build/resources/main/static:/usr/share/nginx/html
      - ./../nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
